### ISSUE TITLE
Added to IH wiki

### ISSUE THREAD

**Issue by houshuang** [DougBurke/astro-haskell#2]
I thought your angular notebook was a great example to include on the IH wiki, however I wanted a version with all the outputs pre-rendered, so I just did "run all cells", and pushed to my own fork. Happy to switch to your version if you have a version with outputs rendered in the future.

https://github.com/gibiansky/IHaskell/wiki

**Comment by DougBurke** [comment]
Thanks. I'm undecided whether to keep a "rendered" view since I like being able to track changes and I find the rendered view adds in a lot of noise. On the other hand, there are lots of advantages to keeping the output.

**Comment by houshuang** [comment]
Yes, ideally it would almost be two files (code, output), because it's good
to have the output, especially if you want to share with others, without
them having to install all your packages, etc. Or maybe the ideal thing
would be for the packages to include a nix hash or something and for the
nbviewer to run the notebook securely in an environment with exactly the
same packages :)

I've also found that even just opening and saving the notebook in a
different version of IPython can create a massive diff due to different
line breaks, formatting etc.

On Tue, Feb 24, 2015 at 7:33 AM, Doug Burke notifications@github.com
wrote:

> Closed #2 https://github.com/DougBurke/astro-haskell/issues/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DougBurke/astro-haskell/issues/2#event-240869373.

## 

http://reganmian.net/blog -- Random Stuff that Matters
